import Head from 'next/head';

const about = () => {
	return (
		<>
			<Head>
				<title>Heal and Hope</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<div className='sub-main-whole-page-container'>
					<BannerAndContent>
						<TitleBanner
							title='About Us'
							subtitle='Heal and Hope chapters and functioning'
						/>
						<MainPageBlock
							containerID='firstMainPageBlock'
							header='McGill University Chapter'
							mainText='It all started from a single club at mcgill, but then it blousemed into something much bigger. We here at heal and hope strive to do important work the best we can. Across the globe.'
							imageSource='/McgillLogo.png'
							imageAlt='Heal And Hope Logo'
						/>
					</BannerAndContent>
					<BannerAndContent>
						<TitleBanner
							title='Partnership logistics'
							subtitle='How we work with The Children Of War Foundation'
						/>
						<img
							alt='diagram of partnership flow'
							src='/PartnershipLogs-removebg.png'
							className='sub-page-large-image'
						/>
					</BannerAndContent>
				</div>
				<PageFooter />
			</main>
		</>
	);
};

const BannerAndContent = ({ children }) => {
	return <div className='sub-page-banner-and-content'>{children}</div>;
};

const PageFooter = () => {
	return (
		<footer>
			<a className='footer-trademark' href='#'>
				Copyright © 2021 heal and hope | www.healandhope.net | All Rights
				Reserved{' '}
			</a>
			<p className='footer-email'>healandhopewebmaster@gmail.com</p>
		</footer>
	);
};

const TitleBanner = ({ title, subtitle }) => {
	return (
		<div className='sub-page-title-banner-container'>
			<h2 className='sub-page-title'>{title}</h2>
			{subtitle && <p className='sub-page-sub-title'>{subtitle}</p>}
		</div>
	);
};

const MainPageBlock = ({
	containerID,
	imageSource,
	imageAlt,
	header,
	mainText,
	buttonText,
}) => {
	return (
		<div className='main-page-section-container' id={containerID}>
			<img src={imageSource} alt={imageAlt} className='main-page-image'></img>
			<div className='main-page-right-side-container'>
				<div className='main-right-side-long-text'>{header}</div>
				<div className='main-right-light-text'>{mainText}</div>
				{buttonText && (
					<button className='main-right-donate-button'>{buttonText}</button>
				)}
			</div>
		</div>
	);
};

export default about;
