import Head from 'next/head';

const about = () => {
	return (
		<>
			<Head>
				<title>Heal and Hope</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<div className='main-whole-page-container'>
					<MainPageBlock
						containerID='firstMainPageBlock'
						header='About Us'
						mainText='It all started from a single club at mcgill, but then it blousemed into something much bigger. We here at heal and hope strive to do important work the best we can. Across the globe.'
						buttonText='Learn More'
						imageSource='/Logo.png'
						imageAlt='Heal And Hope Logo'
					/>
				</div>
				<footer>
					<a className='footer-trademark' href='#'>
						Copyright © 2021 heal and hope | www.healandhope.net | All Rights
						Reserved{' '}
					</a>
					<p className='footer-email'>healandhopewebmaster@gmail.com</p>
				</footer>
			</main>
		</>
	);
};

const MainPageBlock = ({
	containerID,
	imageSource,
	imageAlt,
	header,
	mainText,
	buttonText,
}) => {
	return (
		<div className='main-page-section-container' id={containerID}>
			<img src={imageSource} alt={imageAlt} className='main-page-image'></img>
			<div className='main-page-right-side-container'>
				<div className='main-right-side-long-text'>{header}</div>
				<div className='main-right-light-text'>{mainText}</div>
				<button className='main-right-donate-button'>{buttonText}</button>
			</div>
		</div>
	);
};

export default about;
