import { useRouter } from 'next/router';

import Head from 'next/head';

export default function Home() {
	return (
		<>
			<Head>
				<title>Heal and Hope</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<div className='main-whole-page-container'>
					<div className='spacer'></div>
					<div className='container'>
						<MainPageBlock2
							containerID='firstMainPageBlock'
							header='Student Organization. Global Impact.'
							mainText='Giving children a second chance at life'
							buttonText='Donate Here'
							imageSource='/Logo.png'
							imageAlt='Heal And Hope Logo'
							buttonHREF='/'
						/>
					</div>

					<div className='main-cards-container'>
						<MainPageCard
							titleText='Fundraising Goal:'
							titleNumber='10,000$'
							imageSRC='/fundraising.png'
							imageALT='fundraising hands'
						/>
						<MainPageCard
							titleText='Funds raised:'
							titleNumber='5,000$'
							imageSRC='/fundraisingHeart.png'
							imageALT='fundraising heart'
						/>
						<MainPageCard
							titleText='Surgeries Funded:'
							titleNumber='43'
							imageSRC='/doctor.png'
							imageALT='fundraising doctor'
						/>
					</div>
					<MainPageBlock
						imageSource='/cowfLogo2.png'
						imageAlt='Children of war foundation logo'
						header='Our partner: The Children Of War Fondation'
						mainText='COWF has evolved from saving one life at a time to now being on
					the forefront of systematic change with life enabling healthcare
					and education, all in an effort to heal communities through
					capacity building. COWF continues to build and draw a global
					presence through its remote networks & partners, engaging with
					health care professionals, innovators, educators, scientists,
					private, public, governmental, academic, and institutional
					entities, from across the globe.'
						buttonText='Learn More'
						buttonHREF='/about'
						containerID='secondMainPageBlock'
					/>
				</div>
				<footer>
					<a className='footer-trademark' href='#'>
						Copyright © 2021 heal and hope | www.healandhope.net | All Rights
						Reserved{' '}
					</a>
					<p className='footer-email'>healandhopewebmaster@gmail.com</p>
				</footer>
			</main>
		</>
	);
}

const MainPageBlock2 = ({
	containerID,
	imageSource,
	imageAlt,
	header,
	mainText,
	buttonText,
	buttonHREF,
}) => {
	const router = useRouter();
	return (
		<div className='front-page-section-container' id={containerID}>
			<div className='front-page-section-text-container'>
				<p className='front-page-section-caps-smaller-message'>{header}</p>
				<div className='front-page-section-larger-message'>{mainText}</div>
				<div class='Box-sc-1wo68lt-0 jEiBhi'>
					<a>
						<button
							color='#fff'
							class='Button__ButtonStyled-w61ggs-0 clbKww'
							onClick={() => router.push(buttonHREF)}
						>
							{buttonText}
							<svg
								id='SVGDoc'
								width='18'
								height='12'
								xmlns='http://www.w3.org/2000/svg'
								version='1.1'
								viewBox='0 0 18 12'
								class='Button___StyledSvg-w61ggs-1 kJIzYi'
							>
								<defs></defs>
								<desc>Generated with Avocode.</desc>
								<g>
									<g>
										<title>tail-right</title>
										<g>
											<title>Path</title>
											<path
												d='M1,5.5h16'
												fill-opacity='0'
												fill='#ffffff'
												stroke-linejoin='round'
												stroke-linecap='round'
												stroke-opacity='1'
												stroke='#ffffff'
												stroke-miterlimit='20'
												stroke-width='2'
											></path>
										</g>
										<g>
											<title>Path</title>
											<path
												d='M12,1v0l5,5v0l-5,5v0'
												fill-opacity='0'
												fill='#ffffff'
												stroke-linejoin='round'
												stroke-linecap='round'
												stroke-opacity='1'
												stroke='#ffffff'
												stroke-miterlimit='20'
												stroke-width='2'
											></path>
										</g>
									</g>
								</g>
							</svg>
						</button>
					</a>
				</div>
			</div>
			<img
				src={imageSource}
				alt={imageAlt}
				className='front-page-section-image'
			></img>
		</div>
	);
};

const MainPageBlock = ({
	containerID,
	imageSource,
	imageAlt,
	header,
	mainText,
	buttonText,
	buttonHREF,
}) => {
	const router = useRouter();
	return (
		<div className='main-page-section-container' id={containerID}>
			<img src={imageSource} alt={imageAlt} className='main-page-image'></img>
			<div className='main-page-right-side-container'>
				<div className='main-right-side-long-text'>{header}</div>
				<div className='main-right-light-text'>{mainText}</div>
				<button
					className='main-right-donate-button'
					onClick={() => router.push(buttonHREF)}
				>
					{buttonText}
				</button>
			</div>
		</div>
	);
};

const MainPageCard = ({ imageSRC, imageALT, titleText, titleNumber }) => {
	return (
		<div className='main-card'>
			<h3 className='main-card-title'>{titleText}</h3>
			<div className='main-card-body'>
				<h4 className='main-card-display-number'>{titleNumber}</h4>
			</div>
			<div className='main-card-image-container'>
				<img src={imageSRC} alt={imageALT} width='20%'></img>
			</div>
		</div>
	);
};
