import Head from 'next/head';
import Image from 'next/image';
import Navbar from '../components/Navbar';

export default function Home() {
	return (
		<div>
			<Head>
				<title>Heal and Hope</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<div className='main-page-container'>
					<div className='main-page-left-side-container'>
						<img src='/Logo.png' alt='healandhope logo' width='80%'></img>
					</div>
					<div className='main-page-right-side-container'>
						<div className='main-right-side-long-text'>
							Giving children a second chance at life
						</div>
					</div>
				</div>
				{/* <Image src='/Logo.png' alt='Heal and hope logo' layout='fill'></Image> */}
			</main>
		</div>
	);
}
